apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://chartmuseum.chartmuseum.svc.cluster.local:8080
    chart: nginx-app
    targetRevision: "0.1.0"
    helm:
      valueFiles:
      - $values/nginx-app-values.yaml
  sources:
  - repoURL: http://git-server.git-server.svc.cluster.local/manifest
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
