apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-ssh-known-hosts-cm
  namespace: argocd
data:
  ssh_known_hosts: |
    # Git server known hosts will be added here
---
apiVersion: v1
kind: Secret
metadata:
  name: git-server-ssh-key
  namespace: argocd
type: Opaque
data:
  sshPrivateKey: ""  # Will be populated by setup script
  type: c3No  # "ssh" in base64
  url: ""  # Will be populated by setup script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  server.insecure: "true"
  server.disable.auth: "true"
  repo.server.ssh.agent: "false"
