apiVersion: v1
kind: Namespace
metadata:
  name: git-server
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: git-server-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/git-server
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-local-gitops-server-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-server-pvc
  namespace: git-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-server
  namespace: git-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-server
  template:
    metadata:
      labels:
        app: git-server
    spec:
      containers:
        - name: git-server
          image: moikot/basic-git-server
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /repos
              name: repo-storage
      volumes:
        - name: repo-storage
          persistentVolumeClaim:
            claimName: git-server-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: git-server
  namespace: git-server
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: git-server
